# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  generate_snake_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: docker://platane/snk@sha256:b7835a30ad60660a0c3e1f669187932a7e098fe4949ed7df4ec3beb56c2cfb9f
        with:
          github_user_name: https://github.com/HidayahJadaan

      - name: Save Generated Files
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          mv *.gif *.svg $GITHUB_WORKSPACE/output/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snake-game-output
          path: $GITHUB_WORKSPACE/output/

      - name: Push Changes to Repository
        run: |
          git config --global user.name "HidayahJadaan"
          git config --global user.email "hkaljadaan18@cit.just.edu.jo"
          git add .
          git commit -m "Add snake game animation"
          git push origin master



