name: Generate Snake

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create output directory
        run: mkdir -p $GITHUB_WORKSPACE/output

      - name: Generate Snake Game
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: HidayahJadaan
          gif_out_path: $GITHUB_WORKSPACE/output/github-contribution-grid-snake.gif
          svg_out_path: $GITHUB_WORKSPACE/output/github-contribution-grid-snake.svg

      - name: Push Changes to Repository
        run: |
          git config --global user.name "HidayahJadaan"
          git config --global user.email "hkaljadaan18@cit.just.edu.jo"
          git add .
          git commit -m "Add snake game animation"
          git push origin main # Use your desired branch name, e.g., "main" or "master"

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: output
          keep_history: false
          allow_empty_commit: true
          jekyll: true
        env:
          GITHUB_TOKEN: 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
