name: Generate Snake

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: HidayahJadaan
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Save Generated Files
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          mv dist/*.gif dist/*.svg $GITHUB_WORKSPACE/output/

      - name: Push Changes to Repository
        run: |
          git config --global user.name "HidayahJadaan"
          git config --global user.email "hkaljadaan18@cit.just.edu.jo"
          git add .
          git commit -m "Add snake game animation"
          git push origin master

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: $GITHUB_WORKSPACE/output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
